### ISSUE TITLE
Some questions around bot activities

### ISSUE THREAD

**Issue by EhsanAramide** [kangalioo/rustbot#12]
Hi!

Actually I am not a rust developer (I just understand some common syntaxs in rust) I have two questions I will be happy with your response:

1. How did you handle dependency management?
2. How did you restricte code executions for security reasons? (For example, paths and file system access)

**Comment by kangalioo** [comment]
Both of these aspects are not handled by me, but by the Rust playground (https://play.rust-lang.org). The bot merely uses the playground's API to run code:

https://github.com/kangalioo/rustbot/blob/af29fa927d065d075f66b9d0b5b4cc8b5e471947/src/code_execution/playground/play_eval.rs#L19-L43

For more information about the Rust playground, see https://github.com/integer32llc/rust-playground

**Comment by EhsanAramide** [comment]
Thanks for your response❤
I will check it.
I also close this issue.🌹❤👍
