### ISSUE TITLE
Unclear how exactly report command works only by help

### ISSUE THREAD

**Issue by MultisampledNight** [kangalioo/rustbot#18]
It might be worth noting in the help of the `/report` command that it also includes a link to the last message sent in that channel. This would make clear to use the report command in the problematic channel itself rather than in a channel specifically for bot commands or the like.

The actual report seems to be sent here:

https://github.com/kangalioo/rustbot/blob/fee995b35a8c73ad221cfa7dcb336ed711465830/src/moderation.rs#L159-L176

**Comment by kangalioo** [comment]
Fixed in e18401bbd1262f7ba463c167d8914a996411c163
