### ISSUE TITLE
Add a way to run a gist shared from playground to `play`

### ISSUE THREAD

**Issue by hamza1311** [kangalioo/rustbot#40]
The playground can share code as GitHub gists. The `play` command should be able to take the gist id or the shared URL as argument, execute the code and return it's response.

The argument may be:
- `?play gist=13ba4f487ad1f4d187f37d4ccd9db6a8` (default options)
- `?play https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=13ba4f487ad1f4d187f37d4ccd9db6a8` (options are specified in the URL)

**Comment by gimbles** [comment]
@hamza1311 Just the gist ID is not enough, you need the github user ID as well.
![image](https://user-images.githubusercontent.com/93856041/167329979-4cfef503-32e2-4144-92dd-2c3cd45e53c2.png)

The format is 
`https://gist.github.com/<user id>/<gist id>`

**Comment by hamza1311** [comment]
Not necessarily. The playground always creates a gist on @rust-play. Also, `https://gist.github.com/<gist_id>` also works. That's what the "Direct link to the gist" link in the share section in the playground directs to

**Comment by kangalioo** [comment]
There's no Rust Playground API endpoint to run code from a gist directly as far as I know. Ferris would have to download the code manually with a GET request to `https://api.github.com/gists/{gist_id}` and then execute the code normally.

Feel free to make a PR

**Comment by gimbles** [comment]
The playground *works* on GitHub Gists. Notice the gist parameter on the "permalink to this playground" link. =)

> https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e8b18d12df99a3148d0cdd99c6c489c2

However, this reads the code present in the gist at (notice the same gist id)

> https://gist.github.com/rust-play/e8b18d12df99a3148d0cdd99c6c489c2

It reads from the `rust-play` user gists, so as far as I know, there is no API for making it read from gists outside of the rust-play user.

I think the official Discord server has a playground team? No idea, but it might be worth asking there.

**Comment by kangalioo** [comment]
> The playground works on GitHub Gists. Notice the gist parameter on the "permalink to this playground" link. =)
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e8b18d12df99a3148d0cdd99c6c489c2

Looking at the network requests, the gist parameter seems to be just a shortcut to load the gist data into the playground environment; not something built into the `/execute` API.

![image](https://user-images.githubusercontent.com/21220820/169643745-aa1fe2ba-a13b-442d-9e59-8cc9453f687c.png)

The playground javascript has to make a manual GET request to https://play.rust-lang.org/meta/gist/e8b18d12df99a3148d0cdd99c6c489c2 to retrieve the code and then send it to https://play.rust-lang.org/execute. Ferris would have to do that, too
