### ISSUE TITLE
Ferris breaks when runned in infinite loop

### ISSUE THREAD

**Issue by 0xlilith** [kangalioo/rustbot#8]
```
?play
while true{
println!("NO");
}
```

`error decoding response body: missing field success at line 1 column 84`

Adding a run time period would be nice so if the code runs more than that kill it

**Comment by kangalioo** [comment]
Fixed in cf0107a
![Screenshot_20210810_111847](https://user-images.githubusercontent.com/21220820/128841809-722432e3-524a-4d83-aa0e-178764c6d265.png)
